name: laravelworkflow

on:
  push:
    - master
  pull_request:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

  steps:
    - name: checkout code
      uses: actions@checkoutv2

    - name: run any script
      run: echo hello,world
